# Generated by Django 3.1.1 on 2020-12-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadsetting',
            options={'verbose_name': 'Настройка'},
        ),
    ]
