# Generated by Django 3.1.1 on 2020-12-11 04:14

from django.db import migrations, models
import histories.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_code', models.CharField(max_length=20, verbose_name='SA код')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('kpi_val', models.TextField(verbose_name='Значение КPI')),
                ('kpi_key', models.TextField(verbose_name='Ключ KPI')),
                ('progress_val', models.TextField(verbose_name='Значения прогресса')),
                ('progress_key', models.TextField(verbose_name='Ключ прогресса')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Подразделение')),
                ('sort_id', models.IntegerField(null=True, verbose_name='Сортировка')),
            ],
            options={
                'db_table': 'agents_history',
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('file_name', models.CharField(max_length=100, verbose_name='Название файла')),
                ('file_path', models.FileField(upload_to=histories.models.content_file_name, verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'db_table': 'upload_history',
            },
        ),
    ]
