# Generated by Django 3.1.1 on 2020-12-11 07:11

from django.db import migrations, models
import histories.models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0003_auto_20201211_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код ТП')),
                ('image', models.ImageField(default='images/icons/default_logo.png', null=True, upload_to=histories.models.agent_directory_path, verbose_name='Фото агента')),
            ],
            options={
                'db_table': 'agents_images',
            },
        ),
        migrations.RemoveField(
            model_name='history',
            name='image',
        ),
    ]
