# Generated by Django 3.1.1 on 2020-12-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0004_auto_20201211_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
